name: timesheet_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1  # ✅ Adicionado para salvar PDFs no Firebase

  # ✅ Scanner e manipulação de imagens
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

  # ✅ Outros pacotes utilizados
  font_awesome_flutter: ^10.3.0
  pdf: ^3.6.0
  path_provider: ^2.1.2
  printing: ^5.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  #edge_detection: ^1.1.3
  permission_handler: ^11.3.1
  cunning_document_scanner: ^1.2.3
  cached_network_image: ^3.0.0
  flutter_pdfview: ^1.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
