name: timesheet_app
description: "An app to manage the timesheets of Central Island Floors Inc."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  # ✅ Scanner e manipulação de imagens
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

  # ✅ Outros pacotes utilizados
  font_awesome_flutter: ^10.3.0
  pdf: ^3.6.0
  path_provider: ^2.1.2
  printing: ^5.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  permission_handler: ^11.4.0
  cunning_document_scanner: ^1.2.3
  cached_network_image: ^3.0.0
  flutter_pdfview: ^1.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.1.9
  shared_preferences: ^2.5.3
  timezone: ^0.10.0
  http: ^1.2.1
  dio: ^5.8.0+1
  open_file: ^3.5.10

  # ✅ Hive em runtime
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

  # ✅ Geradores de código (apenas no dev)
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  # assets:
  #   - assets/icon.png
